// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.jejee.entities;

import ee.itcollege.jejee.entities.Intsident;
import java.lang.Long;

privileged aspect Intsident_Roo_Entity {
    
    public static Intsident Intsident.findIntsident(Long id) {
        if (id == null) return null;
        return entityManager().find(Intsident.class, id);
    }
    
}
