// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.jejee.entities;

import ee.itcollege.jejee.entities.Piiripunkt;
import java.lang.Long;

privileged aspect Piiripunkt_Roo_Entity {
    
    public static Piiripunkt Piiripunkt.findPiiripunkt(Long id) {
        if (id == null) return null;
        return entityManager().find(Piiripunkt.class, id);
    }
    
}
