// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.jejee.entities;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Riigi_admin_yksus_Roo_Configurable {
    
    declare @type: Riigi_admin_yksus: @Configurable;
    
}
