// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.jejee.entities;

import ee.itcollege.jejee.entities.Vahtkond;
import java.lang.Long;

privileged aspect Vahtkond_Roo_Entity {
    
    public static Vahtkond Vahtkond.findVahtkond(Long id) {
        if (id == null) return null;
        return entityManager().find(Vahtkond.class, id);
    }
    
}
